// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1mqH317nCo96qIYbVWZfLsb5Uz2rU8mc',
    appId: '1:964805127782:web:2d6d689408f8e29fb807a7',
    messagingSenderId: '964805127782',
    projectId: 'reconnect-8f8e9',
    authDomain: 'reconnect-8f8e9.firebaseapp.com',
    databaseURL: 'https://reconnect-8f8e9-default-rtdb.firebaseio.com',
    storageBucket: 'reconnect-8f8e9.appspot.com',
    measurementId: 'G-YDS5XMVHFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXiKctzYcll1uLs0yig1ASErKICM3ClI',
    appId: '1:964805127782:android:20cbdbd641842194b807a7',
    messagingSenderId: '964805127782',
    projectId: 'reconnect-8f8e9',
    databaseURL: 'https://reconnect-8f8e9-default-rtdb.firebaseio.com',
    storageBucket: 'reconnect-8f8e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC6SXBhwo0XANv8JbI_E7HYclqPge8XKo',
    appId: '1:964805127782:ios:1d90f033bb693d6ab807a7',
    messagingSenderId: '964805127782',
    projectId: 'reconnect-8f8e9',
    databaseURL: 'https://reconnect-8f8e9-default-rtdb.firebaseio.com',
    storageBucket: 'reconnect-8f8e9.appspot.com',
    iosBundleId: 'com.example.reconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC6SXBhwo0XANv8JbI_E7HYclqPge8XKo',
    appId: '1:964805127782:ios:a658928132ac46ffb807a7',
    messagingSenderId: '964805127782',
    projectId: 'reconnect-8f8e9',
    databaseURL: 'https://reconnect-8f8e9-default-rtdb.firebaseio.com',
    storageBucket: 'reconnect-8f8e9.appspot.com',
    iosBundleId: 'com.example.reconnect.RunnerTests',
  );
}
